import { Montserrat} from "next/font/google";
import "./globals.css";
import 'funuicss/css/fun.css'

const font = Montserrat({ subsets: ["latin", 'cyrillic'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      
      <body className={font.className}>{children}</body>
    </html>
  );
}
